version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      ignore:
          - dependency-name: 'mongoose'
            versions: ['5.x']
