sudo: required

language: node_js

node_js:
  - "5"
  - "6"
  - "7"

services:
  - docker

before_install:
  - "docker pull smebberson/alpine-rabbitmq"

before_script:
  - "cd ./idearium-lib"
  - "npm install"

script:
  - "npm run test-travis"

after_script:
  - "npm install codecov && ./node_modules/.bin/codecov"
