coverage:
  notify:
    slack:
      default:
        url: 'https://hooks.slack.com/services/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'
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
  token: 769c1584-cd4d-40a2-b385-ff751d3eeaa0
