version: '2'

services:

  # Dependency.
  rabbitmq:
    image: smebberson/alpine-rabbitmq
    environment:
      - RABBITMQ_USER=lib
      - RABBITMQ_PASS=lib
      - RABBITMQ_ENABLE_MANAGEMENT_PLUGIN=true
      - RABBITMQ_MGMT_PORT=15673

  # A Node.js image to test `idearium-lib`.
  lib:
    build: ./
    volumes:
      - ./idearium-lib:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - "rabbitmq"
