coverage:
  notify:
    slack:
      default:
        url: 'secret:VtZ2rO7vXnfDYabpUvlWU3EwIcXV26eRfBdR1SLOdUcW2jUafa2JVIUU+RwmP1RvT3fPQF8ra07zFPvQvoA0BBDUO+TgjjG1V+6CBeG3+YfZI865LAdAbxJ9TmamTNTx+Hg9z9P1N7/3IuCq1seFIye3C2vif3SllxkKp0JjMJc='
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
