name: '@idearium/certs'
on:
    push:
        paths:
            - 'packages/certs/**'
    release:
        types: [published]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
            - name: Setup yarn
              run: yarn install
    publish:
        if: github.event_name == 'release' && contains(github.ref, '@idearium/certs')
        name: Publish
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  registry-url: https://registry.npmjs.org/
            - name: Setup yarn
              run: yarn install
            - name: Publish (beta)
              if: contains(github.ref, 'beta')
              run: yarn workspace @idearium/certs publish --tag beta --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish
              if: "!contains(github.ref , 'beta')"
              run: yarn workspace @idearium/certs publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
