name: '@idearium/lists'
on:
    push:
        paths:
            - 'packages/lists/**'
    release:
        types: [published]

jobs:
    call-workflow-test:
        uses: idearium/idearium-lib/.github/workflows/test.yml@c25b5abff5bbd69060d203b441d95d7291e8602a
        with:
            workspace: '@idearium/lists'
    publish:
        if: github.event_name == 'release' && contains(github.ref, '@idearium/lists')
        name: Publish
        needs: call-workflow-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  registry-url: https://registry.npmjs.org/
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache yarn
              uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Cache node_modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-
            - name: Setup yarn
              run: yarn install
            - name: Publish (beta)
              if: contains(github.ref, 'beta')
              run: yarn workspace @idearium/lists publish --tag beta --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish
              if: "!contains(github.ref , 'beta')"
              run: yarn workspace @idearium/lists publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
