name: '@idearium/log'
on:
    push:
        paths:
            - 'packages/log/**'
    release:
        types: [published]

jobs:
    call-workflow-test:
        uses: idearium/idearium-lib/.github/workflows/test.yml@4c92ae7789ef993f75052b1c320940dbca8d33ab
        with:
            workspace: '@idearium/log'
    call-workflow-publish:
        needs: call-workflow-test
        uses: idearium/idearium-lib/.github/workflows/publish.yml@328bf7ca2b09ca2ede76f874c9eb95dcea8a576d
        with:
            workspace: '@idearium/log'
