name: '@idearium/phone'
on:
    push:
        paths:
            - 'packages/phone/**'
    release:
        paths:
            - 'packages/phone/**'
        types: [published]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                cache: yarn
                node-version: lts/*
            - run: yarn
            - name: Test
              run: yarn workspace @idearium/phone test
    publish:
        if: github.event_name == 'release' && contains(github.ref, '@idearium/phone-v')
        name: Publish
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                cache: yarn
                node-version: lts/*
            - run: yarn
            - name: Publish (beta)
              if: contains(github.ref, 'beta')
              run: yarn workspace @idearium/phone publish --tag beta --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish
              if: "!contains(github.ref , 'beta')"
              run: yarn workspace @idearium/phone publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
