name: '@idearium/redis'
on:
    push:
        paths:
            - 'packages/redis/**'
    release:
        types: [published]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
            - name: Setup yarn
              run: yarn install
    publish:
        if: github.event_name == 'release' && contains(github.ref, '@idearium/redis')
        name: Publish
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  registry-url: https://registry.npmjs.org/
            - name: Setup yarn
              run: yarn install
            - name: Publish (beta)
              if: contains(github.ref, 'beta')
              run: yarn workspace @idearium/redis publish --tag beta --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish
              if: "!contains(github.ref , 'beta')"
              run: yarn workspace @idearium/redis publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
