name: '@idearium/safe-promise'
on:
    push:
        paths:
            - 'packages/safe-promise/**'

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: '22'
            - run: npm install
            - run: npm test --workspace=@idearium/safe-promise
