name: Setup

on:
    workflow_call:
        inputs:
            lockfile:
                description: 'Path to the yarn.lock file'
                required: true
                type: string

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  cache-dependency-path: ${{ inputs.lockfile }}
                  cache: yarn
                  node-version: 'lts/*'
            - run: yarn install --frozen-lockfile
