name: '@idearium/telemetry'
on:
    push:
        paths:
            - 'packages/telemetry/**'

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: '22'
            - run: npm install
